### ISSUE TITLE
[Bug] Imgur comment links not loading

### ISSUE THREAD

**Issue by Noah-Huppert** [laurencedawson/reddit-sync-development#1857] opened 2018-02-14 16:35 UTC
## Description
Links to imgur images and galleries in the comments fail to load with the error: "Error loading album".

## Scenario (steps to reproduce)

1. Navigate to the comments section of a post
2. Locate a link from imgur.com
3. Click on this link

A few reddit comments with broken links include:

- https://www.reddit.com/r/SweatyPalms/comments/7xf67x/in_honor_of_the_winter_olympics_here_is_a_move/du8ccgg/
- https://www.reddit.com/r/aww/comments/7xheoo/rescued_this_little_guy_from_the_shelter/du8fckv/

## Result(s)

A black screen will flash up very briefly. Followed by a toast with the error message "Error loading album".

## Device Info

    Pixel 2
    8.1.0 security patch Feburary 5, 2018
    v15.1.1 Pro

## Screenshot (recommended)
I created a [screen recording of the issue](https://photos.app.goo.gl/nQeXSoDuudeELzWw2)

**Comment by laurencedawson** [comment] 2018-09-13 13:38
Unable to reproduce this. Closing as this was likely an imgur api issue.

**Closed by laurencedawson** 2018-09-13 13:38 UTC
