### ISSUE TITLE
Random graphical glitches after switching accounts

### ISSUE THREAD

**Issue by richardg867** [laurencedawson/reddit-sync-development#638] opened 2014-07-28 13:45 UTC
On my device (which, if that helps, runs 4.1 and has a low DPI screen), Reddit Sync will sometimes glitch out after switching accounts. Shadows break, cards and thumbnails become invisible, <> buttons lose transparency, sometimes the action bar glitches out as well, among other things.

[Screenshots](http://imgur.com/a/1bSKx) - taken with the latest free version
[Older screenshot](http://i.imgur.com/fW6HkAD.jpg) - taken May 26

**Comment by laurencedawson** [comment] 2015-05-02 23:31
I've been unable to reproduce this issue. Closing for now.

**Closed by laurencedawson** 2015-05-02 23:31 UTC
Labels: bug
