### ISSUE TITLE
[Feature Request] Mark all inbox replies as read.

### ISSUE THREAD

**Issue by neonerz** [laurencedawson/reddit-sync-development#1106] opened 2015-12-20 20:17 UTC
Sometimes when making a post, you end up with a ton of replies. Reddit added a feature to disable inbox replies on comments, but not on posts.

I'd love to be able to mark all new items in my inbox as read.

Example would be if you had 100+ new messages, manually marking them all as read takes forever since currently you have to open your inbox, then click on the message, which opens it up, and then having to hit back to get back to your message list.

Alternatively (or in addition to) maybe make the messages selectable so you could add a "mark selected as read"

**Comment by machinator2** [comment] 2016-01-04 23:43
Duplicate of #1007

**Comment by laurencedawson** [comment] 2016-07-21 15:48
This has since been added. Cheers!

**Closed by laurencedawson** 2016-07-21 15:48 UTC
