### ISSUE TITLE
"<text>"  does not show in comments

### ISSUE THREAD

**Issue by lcc15** [laurencedawson/reddit-sync-development#1100] opened 2015-12-14 12:57 UTC
/r/manga has a bot that automatically links the manga enclosed in <>. I tried it on another subreddit and it appears sync doesn't show the greater than and less than signs and anything inside <> inside comments.

**Comment by machinator2** [comment] 2016-01-04 23:46
Duplicate of #783

**Comment by laurencedawson** [comment] 2016-07-25 23:03
This has been fixed for the next release.

**Closed by laurencedawson** 2016-07-25 23:03 UTC
