### ISSUE TITLE
Reddit links handled improperly when using "load post content" option

### ISSUE THREAD

**Issue by evan-a-a** [laurencedawson/reddit-sync-development#849] opened 2015-03-27 06:52 UTC
When load post content is enabled, tapping or swiping to view the link opens the in-app browser instead of opening in the native thread view 

http://i.imgur.com/ouX44aQ.jpg

**Comment by laurencedawson** [comment] 2015-04-06 20:12
Do you have an example of a link that causes this to happen? Thanks.

**Comment by linuxman94** [comment] 2015-04-06 20:17
The easiest example is in /r/bestoff. https://www.reddit.com/r/bestof/comments/31nklf/solaroperated_company_does_an_ama_user_calls_the/

Opening that in reddit sync then following the link with "load post content" enabled reproduces the bug.

**Comment by sirajrauff** [comment] 2015-07-14 14:15
This seems to be an issue with any link to a thread/comment. If you click it in your feed it'll load the comment/thread, however if you're in the comment view it'll load the web version. For exmaple, this post on my frontpage:
![screenshot_20150714-101204](https://cloud.githubusercontent.com/assets/12627851/8675283/f8230202-2a10-11e5-86b3-90feee008d0d.png) 

If I click it, it takes me to the appropriate comment:
![screenshot_20150714-101208](https://cloud.githubusercontent.com/assets/12627851/8675293/0f1cbbc4-2a11-11e5-8723-98d33977b169.png)

If, however, I click on the link from the 'comments' view here:
![screenshot_20150714-101213](https://cloud.githubusercontent.com/assets/12627851/8675308/1cd7bde0-2a11-11e5-9a8d-bd31398cfafe.png)

It loads the web version:
![screenshot_20150714-101218](https://cloud.githubusercontent.com/assets/12627851/8675314/2a61e760-2a11-11e5-8528-f33cc23badba.png)

**Comment by laurencedawson** [comment] 2016-07-21 11:13
Closing as this feature has been removed in lieu of Chrome Custom Tabs. Cheers!

**Closed by laurencedawson** 2016-07-21 11:13 UTC
Labels: blocked, bug
