### ISSUE TITLE
Add ability to disable download button

### ISSUE THREAD

**Issue by tgeliot** [laurencedawson/reddit-sync-development#1121] opened 2016-01-07 06:47 UTC
On my little cell phone, the Download button is very close to the phone's Back button.  The result is that I pretty frequently accidentally download images that I have no interest in saving.  I would like to be able to either disable the download button, or have it require a confirmation, or something to prevent these accidental downloads.

Thank you for your consideration.

**Comment by machinator2** [comment] 2016-01-07 23:56
Partial duplicate of #1020

**Comment by tgeliot** [comment] 2016-01-08 04:05
Indeed, thanks.

Topher Eliot
eliot@alum.mit.edu
"Give me your tired, your poor,
Your huddled masses yearning to breathe free,
The wretched refuse of your teeming shore.
Send these, the homeless, tempest-tossed to me,
I lift my lamp beside the golden door!"

**Comment by laurencedawson** [comment] 2016-03-24 15:17
Duplicate.

**Closed by laurencedawson** 2016-03-24 15:17 UTC
