### ISSUE TITLE
Remove "Mark as Read" for Posts Already Marked as Read

### ISSUE THREAD

**Issue by tenkuu** [laurencedawson/reddit-sync-development#1606] opened 2016-12-04 03:41 UTC
When a post has been marked as read, I think the "mark as read" option in the overflow menu should switch to "mark as unread" or disappear.

**Comment by machinator2** [comment] 2016-12-05 21:33
Duplicate of #1291

**Comment by tenkuu** [comment] 2016-12-05 22:01
Not really. My issue is that the "mark as read" option is still there (and does nothing) for posts that are already marked as read.

**Comment by laurencedawson** [comment] 2016-12-11 22:57
There's no API endpoint to mark as unread.

**Comment by laurencedawson** [comment] 2017-01-13 12:43
Added for the next release.

**Closed by laurencedawson** 2017-01-13 12:43 UTC
