### ISSUE TITLE
Auto Nightmode [feature request]

### ISSUE THREAD

**Issue by Fszeker** [laurencedawson/reddit-sync-development#731] opened 2015-01-10 21:52 UTC
As a lot of people agree it'd be great to have a Auto Night mode:

> Is it possible to bring auto night mode which would automatically set night mode between certain hours? 

> A user controlled setting: Enabling checkbox, Night mode start time, Night mode end time.

> /u/fszeker, [reddit](http://www.reddit.com/r/redditsync/comments/2qv0tx/auto_night_mode_request/)

You could probably make this something like [this](http://www.androidtipsandhacks.com/wp-content/uploads/2014/10/gravitybox-quiet-hours.jpg)

**Comment by laurencedawson** [comment] 2015-02-05 22:57
Closing as this is a duplicate of:

https://github.com/laurencedawson/reddit-sync-development/issues/223

But thanks for the report and for the screenshot.

**Closed by laurencedawson** 2015-02-05 22:57 UTC
