### ISSUE TITLE
Put in a damn "mark all as read" button at least!

### ISSUE THREAD

**Issue by gaveasky** [laurencedawson/reddit-sync-development#1070] opened 2015-11-02 10:16 UTC
When you open your inbox, it should automatically mark all messages as 'read' , I should NOT have to individually open every single message just to clear my inbox (which sometimes has more than 100 messages in it)

Laurence, did you actually even stop to think for one second before building this into your app? I've used sync in the past but left because of this issue. I come back a year later and it is still not fixed. This is ridiculous.

**Comment by okungnyo** [comment] 2015-11-02 13:16
No, YOU are being ridiculous.

You think that the way that YOU do things should somehow be the way EVERYONE does things?

How old are you 12? Boy, I can already imagine how you will be when you discover politics.

Why the heck should opening the inbox automatically mark all messages as read?

Do you expect all your emails to be archived automatically as soon as you open your inbox?

Do you expect all your notifications to be cleared and disappear as soon as you pull down the notification drawer on your phone?

Do you expect your children to give you grandkids before they're even born?

**Comment by deronsizemore** [comment] 2015-11-07 12:52
I think a mark all as read button would be nice. I wouldn't like all my notifications to be marked as read upon opening the messages window though.

**Comment by machinator2** [comment] 2016-01-04 23:44
Duplicate of #1007

**Comment by laurencedawson** [comment] 2016-07-21 15:48
This has since been added.

**Closed by laurencedawson** 2016-07-21 15:48 UTC
