### ISSUE TITLE
Change color of gray text

### ISSUE THREAD

**Issue by generalissimo8** [laurencedawson/reddit-sync-development#729] opened 2015-01-03 15:58 UTC
I find the gray text too hard too read (especially since it is serif). It would be great if there was an option to change it to black and sans-serif.

**Comment by Feltzer** [comment] 2015-05-09 14:26
I agree, but this is a duplicate of #714.

**Comment by laurencedawson** [comment] 2016-07-25 21:56
Closing duplicate.

**Closed by laurencedawson** 2016-07-25 21:56 UTC
