### ISSUE TITLE
Images are not loading

### ISSUE THREAD

**Issue by CodeGiver123** [laurencedawson/reddit-sync-development#502] opened 2014-01-30 16:17 UTC
I left a post on Reddit about this before I realized this was the proper place for it.

I am having an issue where images do not load in reddit sync. Not in the card view or in the image viewer. I have attached screenshots as well.
I have a Verizon Galaxy Nexus on 4.42 using ShinyROM.
Thanks!
http://imgur.com/a/ZZEwz

I have tried reinstalling the app but it has the same behavior.

**Comment by laurencedawson** [comment] 2015-04-19 22:00
Closing due to lack of information.

**Closed by laurencedawson** 2015-04-19 22:00 UTC
Labels: bug

**Comment by KayAteChef** [comment] 2016-05-09 14:24
I am having the same issue.

On my Galaxy S5 I had no problem with Sync for Reddit.
My S5 broke so I retrieved my old Galaxy S2 from the parts bin and installed Sync for Reddit. It doesn't load images.

The problem is as CodeGiver123 describes:
Open the app. Cards have no images loaded. Tap the unloaded image and get "Error 404: File not found." Select 'open in browser' and that works.

I never used Sync on the S2 until recently, so I can't say whether it ever would have worked on this phone. But I have a suspicion that it relates to the read/write sd card permissions issue I have on this phone since upgrading it to Android 4.1.2.

I can't save any files using any download manager. CodeGiver123 may have had the same issue 2 years ago.
