### ISSUE TITLE
[Feature Request] Comment Search/Ctrl f/Find in page for comments

### ISSUE THREAD

**Issue by rlx3** [laurencedawson/reddit-sync-development#1112] opened 2015-12-30 19:36 UTC
Searching within subreddits is great but having the ability to sift through threads by searching comments would be great as I often use it when browsing reddit on desktop.

**Comment by machinator2** [comment] 2016-01-04 23:42
Duplicate of #466

**Comment by laurencedawson** [comment] 2016-07-21 10:35
This has since been added. 

Cheers!

**Closed by laurencedawson** 2016-07-21 10:35 UTC
