### ISSUE TITLE
Post Nav - Volume Up/Down to navigate post list (similar to comment nav)

### ISSUE THREAD

**Issue by bmcclure937** [laurencedawson/reddit-sync-development#1237] opened 2016-07-28 15:58 UTC

**Comment by machinator2** [comment] 2016-07-28 16:50
Duplicate of #1184

**Comment by laurencedawson** [comment] 2017-01-08 22:49
Duplicate:

https://github.com/laurencedawson/reddit-sync-development/issues/1184

Closing.

**Closed by laurencedawson** 2017-01-08 22:49 UTC
