### ISSUE TITLE
Viewing user profile with lots of trophies doesn't scroll well with swipe-back.

### ISSUE THREAD

**Issue by nguyenmp** [laurencedawson/reddit-sync-development#992] opened 2015-07-03 23:13 UTC
Try https://www.reddit.com/u/chooter on 10.7.21

If you swipe to see more , oyu can not swipe back because it triggers the swipe back to previous activity.

**Comment by machinator2** [comment] 2016-07-22 15:29
Duplicate of #946

**Comment by laurencedawson** [comment] 2016-07-22 17:14
Merging with #946

**Closed by laurencedawson** 2016-07-22 17:14 UTC
